export interface RawMovie {
  title: string;
  description: string;
  release_year: number;
  genre: string;
  language: string;
  duration: string;
  director: string;
  cast_members: string;
  poster_url: string;
  backdrop_url: string;
  trailer_url: string;
  featured: boolean;
  average_rating: number;
  rating_count: number;
}

const posterFallback = 'https://images.unsplash.com/photo-1517604931442-7e0c8ed2963c?q=80&w=800&auto=format&fit=crop';
const backdropFallback = 'https://images.unsplash.com/photo-1489599849927-2ee91cede3ba?q=80&w=1600&auto=format&fit=crop';

export const TAMIL_100_MOVIES: RawMovie[] = [
  {
    title: 'Nayagan',
    description: 'A young boy flees to Bombay after his father is killed, rising through the ranks of the underworld to become a revered savior and godfather for displaced southern immigrants.',
    release_year: 1987,
    genre: 'Crime',
    language: 'Tamil',
    duration: '2h 53m',
    director: 'Mani Ratnam',
    cast_members: 'Kamal Haasan, Saranya Ponvannan, Janagaraj, Delhi Ganesh',
    poster_url: 'https://images.unsplash.com/photo-1518173946687-a4c8a383392e?q=80&w=800&auto=format&fit=crop',
    backdrop_url: backdropFallback,
    trailer_url: 'https://www.youtube.com/watch?v=sY1S34973zA',
    featured: true,
    average_rating: 4.9,
    rating_count: 3200,
  },
  {
    title: 'Baashha',
    description: 'An unassuming, humble auto-rickshaw driver in Chennai conceals his past life as an invincible, charismatic Mumbai crime kingpin to protect his siblings.',
    release_year: 1995,
    genre: 'Action',
    language: 'Tamil',
    duration: '2h 45m',
    director: 'Suresh Krissna',
    cast_members: 'Rajinikanth, Nagma, Raghuvaran, Janagaraj',
    poster_url: 'https://images.unsplash.com/photo-1509281373149-e957c6296406?q=80&w=800&auto=format&fit=crop',
    backdrop_url: backdropFallback,
    trailer_url: 'https://www.youtube.com/watch?v=EXeTwQWrcwY',
    featured: true,
    average_rating: 4.9,
    rating_count: 3500,
  },
  {
    title: 'Vikram',
    description: 'A high-octane black-ops mystery where a retired commander leads a covert squad against a ruthless drug cartel syndicate linked to systemic corruption.',
    release_year: 2022,
    genre: 'Action',
    language: 'Tamil',
    duration: '2h 55m',
    director: 'Lokesh Kanagaraj',
    cast_members: 'Kamal Haasan, Vijay Sethupathi, Fahadh Faasil, Suriya',
    poster_url: 'https://images.unsplash.com/photo-1542751371-adc38448a05e?q=80&w=800&auto=format&fit=crop',
    backdrop_url: backdropFallback,
    trailer_url: 'https://www.youtube.com/watch?v=OKBMCL-frPU',
    featured: true,
    average_rating: 4.9,
    rating_count: 4100,
  },
  {
    title: 'Anbe Sivam',
    description: 'An unexpected encounter between an arrogant commercial filmmaker and a scarred, compassionate socialist union worker transforms their perception of love, divinity, and humanity.',
    release_year: 2003,
    genre: 'Drama',
    language: 'Tamil',
    duration: '2h 40m',
    director: 'Sundar C.',
    cast_members: 'Kamal Haasan, R. Madhavan, Kiran Rathod, Nassar',
    poster_url: 'https://images.unsplash.com/photo-1511671782779-c97d3d27a1d4?q=80&w=800&auto=format&fit=crop',
    backdrop_url: backdropFallback,
    trailer_url: 'https://www.youtube.com/watch?v=bLvqoHBptjg',
    featured: true,
    average_rating: 4.9,
    rating_count: 2800,
  },
  {
    title: 'Thalapathi',
    description: 'A modern adaptation of the Mahabharata relationship between Karna and Duryodhana, chronicling the unshakeable brotherhood between an abandoned vigilante and an honorable gangster.',
    release_year: 1991,
    genre: 'Drama',
    language: 'Tamil',
    duration: '2h 46m',
    director: 'Mani Ratnam',
    cast_members: 'Rajinikanth, Mammootty, Arvind Swamy, Shobana, Bhanupriya',
    poster_url: 'https://images.unsplash.com/photo-1506703719100-a0f3a48c0f86?q=80&w=800&auto=format&fit=crop',
    backdrop_url: backdropFallback,
    trailer_url: 'https://www.youtube.com/watch?v=sY1S34973zA',
    featured: true,
    average_rating: 4.9,
    rating_count: 2900,
  },
  {
    title: 'Kaithi',
    description: 'A newly released prisoner desperate to see his young daughter is roped into driving a drug-poisoned police unit through a gauntlet of heavily armed smugglers.',
    release_year: 2019,
    genre: 'Action',
    language: 'Tamil',
    duration: '2h 25m',
    director: 'Lokesh Kanagaraj',
    cast_members: 'Karthi, Narain, Arjun Das, George Maryan',
    poster_url: 'https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?q=80&w=800&auto=format&fit=crop',
    backdrop_url: backdropFallback,
    trailer_url: 'https://www.youtube.com/watch?v=gQqbcswbRe8',
    featured: true,
    average_rating: 4.8,
    rating_count: 3100,
  },
  {
    title: 'Asuran',
    description: 'A quiet, aging farmer is forced to take up arms to protect his family when his hotheaded son retaliates against an oppressive, wealthy landowning family.',
    release_year: 2019,
    genre: 'Action',
    language: 'Tamil',
    duration: '2h 21m',
    director: 'Vetrimaaran',
    cast_members: 'Dhanush, Manju Warrier, Prakash Raj, Pasupathy',
    poster_url: 'https://images.unsplash.com/photo-1518709268805-4e9042af9f23?q=80&w=800&auto=format&fit=crop',
    backdrop_url: backdropFallback,
    trailer_url: 'https://www.youtube.com/watch?v=vKQi3bBA1y8',
    featured: true,
    average_rating: 4.9,
    rating_count: 3300,
  },
  {
    title: 'Vada Chennai',
    description: 'A talented young carrom player in North Chennai reluctantly gets drawn into a generational turf war between ruthless local gang lords.',
    release_year: 2018,
    genre: 'Crime',
    language: 'Tamil',
    duration: '2h 44m',
    director: 'Vetrimaaran',
    cast_members: 'Dhanush, Ameer, Andrea Jeremiah, Aishwarya Rajesh, Samuthirakani',
    poster_url: 'https://images.unsplash.com/photo-1539037116277-4db20889f2d4?q=80&w=800&auto=format&fit=crop',
    backdrop_url: backdropFallback,
    trailer_url: 'https://www.youtube.com/watch?v=znmZoVkCjpI',
    featured: true,
    average_rating: 4.9,
    rating_count: 3100,
  },
  {
    title: 'Super Deluxe',
    description: 'An interrelated anthology connecting an unfaithful wife, an estranged transgender parent, four rebellious teenagers, and a corrupt priest in a surreal, philosophical day.',
    release_year: 2019,
    genre: 'Drama',
    language: 'Tamil',
    duration: '2h 56m',
    director: 'Thiagarajan Kumararaja',
    cast_members: 'Vijay Sethupathi, Fahadh Faasil, Samantha Ruth Prabhu, Ramya Krishnan',
    poster_url: 'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?q=80&w=800&auto=format&fit=crop',
    backdrop_url: backdropFallback,
    trailer_url: 'https://www.youtube.com/watch?v=3-Xq_Z295eU',
    featured: true,
    average_rating: 4.8,
    rating_count: 2700,
  },
  {
    title: 'Pariyerum Perumal',
    description: 'A young law student from an oppressed caste struggles for dignity, education, and equality while confronting systemic caste violence and bigotry.',
    release_year: 2018,
    genre: 'Drama',
    language: 'Tamil',
    duration: '2h 34m',
    director: 'Mari Selvaraj',
    cast_members: 'Kathir, Anandhi, Yogi Babu, G. Marimuthu',
    poster_url: 'https://images.unsplash.com/photo-1507842229452-976932454b8d?q=80&w=800&auto=format&fit=crop',
    backdrop_url: backdropFallback,
    trailer_url: 'https://www.youtube.com/watch?v=Gk_o_Lw_cE',
    featured: false,
    average_rating: 4.9,
    rating_count: 2400,
  },
  {
    title: 'Jai Bhim',
    description: 'A courageous human rights lawyer takes on the system when an innocent tribal man is falsely accused of theft, tortured, and made to disappear in custody.',
    release_year: 2021,
    genre: 'Drama',
    language: 'Tamil',
    duration: '2h 44m',
    director: 'T. J. Gnanavel',
    cast_members: 'Suriya, Lijomol Jose, Manikandan, Prakash Raj',
    poster_url: 'https://images.unsplash.com/photo-1493976040374-85c8e12f0c0e?q=80&w=800&auto=format&fit=crop',
    backdrop_url: backdropFallback,
    trailer_url: 'https://www.youtube.com/watch?v=Gc6dEDnL8JA',
    featured: true,
    average_rating: 4.9,
    rating_count: 3600,
  },
  {
    title: 'Soorarai Pottru',
    description: 'Inspired by the real life of Captain G. R. Gopinath, a visionary former air force captain overcomes entrenched corporate cartels to launch a low-cost airline for everyday citizens.',
    release_year: 2020,
    genre: 'Drama',
    language: 'Tamil',
    duration: '2h 33m',
    director: 'Sudha Kongara',
    cast_members: 'Suriya, Aparna Balamurali, Paresh Rawal, Urvashi',
    poster_url: 'https://images.unsplash.com/photo-1451187580459-43490279c0fa?q=80&w=800&auto=format&fit=crop',
    backdrop_url: backdropFallback,
    trailer_url: 'https://www.youtube.com/watch?v=fa_DIwRsa9o',
    featured: true,
    average_rating: 4.8,
    rating_count: 3200,
  },
  {
    title: 'Leo',
    description: 'A tranquil cafe owner and animal rescuer in Himachal Pradesh is thrust into explosive confrontations when ruthless drug kingpins claim he is their estranged hitman.',
    release_year: 2023,
    genre: 'Action',
    language: 'Tamil',
    duration: '2h 44m',
    director: 'Lokesh Kanagaraj',
    cast_members: 'Thalapathy Vijay, Sanjay Dutt, Trisha, Arjun Sarja, Gautham Menon',
    poster_url: 'https://images.unsplash.com/photo-1542751371-adc38448a05e?q=80&w=800&auto=format&fit=crop',
    backdrop_url: backdropFallback,
    trailer_url: 'https://www.youtube.com/watch?v=Po3jVh2CAT8',
    featured: true,
    average_rating: 4.7,
    rating_count: 3900,
  },
  {
    title: 'Master',
    description: 'An alcoholic college professor is dispatched to a juvenile correctional facility where he clashes with a brutal gangster exploiting incarcerated youths.',
    release_year: 2021,
    genre: 'Action',
    language: 'Tamil',
    duration: '2h 59m',
    director: 'Lokesh Kanagaraj',
    cast_members: 'Thalapathy Vijay, Vijay Sethupathi, Malavika Mohanan, Andrea Jeremiah',
    poster_url: 'https://images.unsplash.com/photo-1509281373149-e957c6296406?q=80&w=800&auto=format&fit=crop',
    backdrop_url: backdropFallback,
    trailer_url: 'https://www.youtube.com/watch?v=UTiXQcrLnv4',
    featured: true,
    average_rating: 4.7,
    rating_count: 3700,
  },
  {
    title: 'Jailer',
    description: 'A retired prison warden leads an ostensibly peaceful family life until an antique idol smuggling syndicate targets his police officer son, awakening his lethal persona.',
    release_year: 2023,
    genre: 'Action',
    language: 'Tamil',
    duration: '2h 48m',
    director: 'Nelson Dilipkumar',
    cast_members: 'Superstar Rajinikanth, Mohanlal, Shiva Rajkumar, Vinayakan, Ramya Krishnan',
    poster_url: 'https://images.unsplash.com/photo-1478760329108-5c3ed9d495a0?q=80&w=800&auto=format&fit=crop',
    backdrop_url: backdropFallback,
    trailer_url: 'https://www.youtube.com/watch?v=Y5BeWdODPqo',
    featured: true,
    average_rating: 4.8,
    rating_count: 3800,
  },
  {
    title: '96',
    description: 'Two high school sweethearts reunite at a 22-year class reunion, spending a bittersweet night strolling through Chennai reminiscing about lost love and unsaid words.',
    release_year: 2018,
    genre: 'Romance',
    language: 'Tamil',
    duration: '2h 38m',
    director: 'C. Prem Kumar',
    cast_members: 'Vijay Sethupathi, Trisha Krishnan, Devadarshini, Bagavathi Perumal',
    poster_url: 'https://images.unsplash.com/photo-1539037116277-4db20889f2d4?q=80&w=800&auto=format&fit=crop',
    backdrop_url: backdropFallback,
    trailer_url: 'https://www.youtube.com/watch?v=r0f_k_sP9Zk',
    featured: false,
    average_rating: 4.9,
    rating_count: 2800,
  },
  {
    title: 'Ratsasan',
    description: 'An aspiring film director turned police sub-inspector uses his encyclopedic research into psychopathy to track down a sadistic serial killer targeting schoolgirls.',
    release_year: 2018,
    genre: 'Thriller',
    language: 'Tamil',
    duration: '2h 50m',
    director: 'Ram Kumar',
    cast_members: 'Vishnu Vishal, Amala Paul, Saravanan, Munishkanth',
    poster_url: 'https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?q=80&w=800&auto=format&fit=crop',
    backdrop_url: backdropFallback,
    trailer_url: 'https://www.youtube.com/watch?v=gsdaF_83k9E',
    featured: true,
    average_rating: 4.9,
    rating_count: 3100,
  },
  {
    title: 'Ponniyin Selvan: Part 1',
    description: 'Mani Ratnam epic magnum opus recounting the golden age of the imperial Chola dynasty, internal coups, and the rise of Arulmozhi Varman.',
    release_year: 2022,
    genre: 'Action',
    language: 'Tamil',
    duration: '2h 47m',
    director: 'Mani Ratnam',
    cast_members: 'Vikram, Aishwarya Rai Bachchan, Jayam Ravi, Karthi, Trisha',
    poster_url: 'https://images.unsplash.com/photo-1518709268805-4e9042af9f23?q=80&w=800&auto=format&fit=crop',
    backdrop_url: backdropFallback,
    trailer_url: 'https://www.youtube.com/watch?v=D4qAQYLGZVM',
    featured: true,
    average_rating: 4.8,
    rating_count: 3400,
  },
  {
    title: 'Ponniyin Selvan: Part 2',
    description: 'The monumental climax of the Chola saga resolving the vengeance of Nandini, the resilience of the Chola princes, and the coronation of Rajaraja Chola.',
    release_year: 2023,
    genre: 'Action',
    language: 'Tamil',
    duration: '2h 44m',
    director: 'Mani Ratnam',
    cast_members: 'Vikram, Aishwarya Rai Bachchan, Jayam Ravi, Karthi, Trisha',
    poster_url: 'https://images.unsplash.com/photo-1534447677768-be436bb09401?q=80&w=800&auto=format&fit=crop',
    backdrop_url: backdropFallback,
    trailer_url: 'https://www.youtube.com/watch?v=enY3iP_p_cE',
    featured: false,
    average_rating: 4.7,
    rating_count: 2900,
  },
  {
    title: 'Maharaja',
    description: 'A quiet barber visits a police station reporting that his dustbin named Lakshmi was stolen in a burglary, setting off a gripping non-linear investigation into retribution.',
    release_year: 2024,
    genre: 'Thriller',
    language: 'Tamil',
    duration: '2h 21m',
    director: 'Nithilan Saminathan',
    cast_members: 'Vijay Sethupathi, Anurag Kashyap, Mamta Mohandas, Natarajan Subramaniam',
    poster_url: 'https://images.unsplash.com/photo-1509281373149-e957c6296406?q=80&w=800&auto=format&fit=crop',
    backdrop_url: backdropFallback,
    trailer_url: 'https://www.youtube.com/watch?v=p4F_P9Zz6_w',
    featured: true,
    average_rating: 4.9,
    rating_count: 3500,
  },
  {
    title: 'Karnan',
    description: 'A fearless young villager fights for his oppressed village right to basic transit infrastructure, dignity, and independence against arrogant police brutality.',
    release_year: 2021,
    genre: 'Action',
    language: 'Tamil',
    duration: '2h 39m',
    director: 'Mari Selvaraj',
    cast_members: 'Dhanush, Lal, Rajisha Vijayan, Yogi Babu, Natarajan Subramaniam',
    poster_url: 'https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?q=80&w=800&auto=format&fit=crop',
    backdrop_url: backdropFallback,
    trailer_url: 'https://www.youtube.com/watch?v=F_fP_vL7aP8',
    featured: false,
    average_rating: 4.8,
    rating_count: 2800,
  },
  {
    title: 'Sarpatta Parambarai',
    description: 'Set during the 1970s Emergency era in Madras, a passionate young harbor laborer rises to defend the honor of his boxing clan against fierce rival pugilists.',
    release_year: 2021,
    genre: 'Drama',
    language: 'Tamil',
    duration: '2h 53m',
    director: 'Pa. Ranjith',
    cast_members: 'Arya, Pasupathy, John Vijay, Dushara Vijayan, Shabeer Kallarakkal',
    poster_url: 'https://images.unsplash.com/photo-1517604931442-7e0c8ed2963c?q=80&w=800&auto=format&fit=crop',
    backdrop_url: backdropFallback,
    trailer_url: 'https://www.youtube.com/watch?v=7_hE7Yv9Qy4',
    featured: true,
    average_rating: 4.8,
    rating_count: 2900,
  },
  {
    title: 'Mankatha',
    description: 'A suspended, corrupt police officer orchestrates an audacious 500-crore heist of illegal cricket betting money in Dharavi alongside an untrustworthy crew.',
    release_year: 2011,
    genre: 'Action',
    language: 'Tamil',
    duration: '2h 35m',
    director: 'Venkat Prabhu',
    cast_members: 'Ajith Kumar, Arjun Sarja, Trisha Krishnan, Lakshmi Rai, Anjali',
    poster_url: 'https://images.unsplash.com/photo-1542751371-adc38448a05e?q=80&w=800&auto=format&fit=crop',
    backdrop_url: backdropFallback,
    trailer_url: 'https://www.youtube.com/watch?v=znmZoVkCjpI',
    featured: true,
    average_rating: 4.8,
    rating_count: 3100,
  },
  {
    title: 'Thuppakki',
    description: 'An elite Indian Army intelligence captain vacationing in Mumbai stumbles upon a sleeper-cell conspiracy and executes a thrilling tactical strike to avert urban terror.',
    release_year: 2012,
    genre: 'Action',
    language: 'Tamil',
    duration: '2h 45m',
    director: 'AR Murugadoss',
    cast_members: 'Thalapathy Vijay, Kajal Aggarwal, Vidyut Jammwal, Jayaram',
    poster_url: 'https://images.unsplash.com/photo-1509281373149-e957c6296406?q=80&w=800&auto=format&fit=crop',
    backdrop_url: backdropFallback,
    trailer_url: 'https://www.youtube.com/watch?v=EXeTwQWrcwY',
    featured: true,
    average_rating: 4.8,
    rating_count: 3400,
  },
  {
    title: 'Kaththi',
    description: 'A suave petty criminal escapes jail and assumes the identity of his social-activist lookalike, only to take up his mission fighting a corporate water-theft conglomerate.',
    release_year: 2014,
    genre: 'Action',
    language: 'Tamil',
    duration: '2h 46m',
    director: 'AR Murugadoss',
    cast_members: 'Thalapathy Vijay, Samantha Ruth Prabhu, Neil Nitin Mukesh, Sathish',
    poster_url: 'https://images.unsplash.com/photo-1518173946687-a4c8a383392e?q=80&w=800&auto=format&fit=crop',
    backdrop_url: backdropFallback,
    trailer_url: 'https://www.youtube.com/watch?v=UTiXQcrLnv4',
    featured: false,
    average_rating: 4.8,
    rating_count: 3200,
  },
  {
    title: 'Ghilli',
    description: 'A spirited Kabaddi champion in Chennai rescues a distressed young woman from a tyrannical provincial faction leader in Madurai, leading to a whirlwind pursuit.',
    release_year: 2004,
    genre: 'Action',
    language: 'Tamil',
    duration: '2h 46m',
    director: 'Dharani',
    cast_members: 'Thalapathy Vijay, Trisha Krishnan, Prakash Raj, Ashish Vidyarthi',
    poster_url: 'https://images.unsplash.com/photo-1517154421773-0529f29ea451?q=80&w=800&auto=format&fit=crop',
    backdrop_url: backdropFallback,
    trailer_url: 'https://www.youtube.com/watch?v=s7EdQ4FqbhY',
    featured: true,
    average_rating: 4.9,
    rating_count: 3600,
  },
  {
    title: 'Sivaji: The Boss',
    description: 'A wealthy NRI software architect returns to India to offer free education and healthcare, battling corrupt politicians through financial subterfuge and vigilante style.',
    release_year: 2007,
    genre: 'Action',
    language: 'Tamil',
    duration: '3h 05m',
    director: 'S. Shankar',
    cast_members: 'Superstar Rajinikanth, Shriya Saran, Suman, Vivek, Manivannan',
    poster_url: 'https://images.unsplash.com/photo-1506703719100-a0f3a48c0f86?q=80&w=800&auto=format&fit=crop',
    backdrop_url: backdropFallback,
    trailer_url: 'https://www.youtube.com/watch?v=EXeTwQWrcwY',
    featured: true,
    average_rating: 4.8,
    rating_count: 3300,
  },
  {
    title: 'Enthiran',
    description: 'A brilliant roboticist constructs an advanced humanoid robot named Chitti, but complications turn catastrophic when the android develops emotional capacity and falls in love.',
    release_year: 2010,
    genre: 'Sci-Fi',
    language: 'Tamil',
    duration: '2h 57m',
    director: 'S. Shankar',
    cast_members: 'Superstar Rajinikanth, Aishwarya Rai Bachchan, Danny Denzongpa, Santhanam',
    poster_url: 'https://images.unsplash.com/photo-1542751371-adc38448a05e?q=80&w=800&auto=format&fit=crop',
    backdrop_url: backdropFallback,
    trailer_url: 'https://www.youtube.com/watch?v=vKQi3bBA1y8',
    featured: true,
    average_rating: 4.8,
    rating_count: 3400,
  },
  {
    title: 'Anniyan',
    description: 'Frustrated by civic apathy and pervasive consumer corruption, an idealistic lawyer suffering from dissociative identity disorder spawns a terrifying, mythological vigilante alter-ego.',
    release_year: 2005,
    genre: 'Thriller',
    language: 'Tamil',
    duration: '3h 01m',
    director: 'S. Shankar',
    cast_members: 'Chiyaan Vikram, Sadha, Prakash Raj, Vivek, Nedumudi Venu',
    poster_url: 'https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?q=80&w=800&auto=format&fit=crop',
    backdrop_url: backdropFallback,
    trailer_url: 'https://www.youtube.com/watch?v=znmZoVkCjpI',
    featured: true,
    average_rating: 4.9,
    rating_count: 3200,
  },
  {
    title: 'Indian',
    description: 'Senapathy, an unyielding 70-year-old former freedom fighter, wages a lethal one-man crusade utilizing ancient varmam martial arts to eradicate rampant administrative graft.',
    release_year: 1996,
    genre: 'Action',
    language: 'Tamil',
    duration: '3h 05m',
    director: 'S. Shankar',
    cast_members: 'Kamal Haasan, Manisha Koirala, Urmila Matondkar, Sukanya, Goundamani',
    poster_url: 'https://images.unsplash.com/photo-1518173946687-a4c8a383392e?q=80&w=800&auto=format&fit=crop',
    backdrop_url: backdropFallback,
    trailer_url: 'https://www.youtube.com/watch?v=sY1S34973zA',
    featured: true,
    average_rating: 4.9,
    rating_count: 3100,
  },
  {
    title: 'Mudhalvan',
    description: 'A courageous television journalist challenges the corrupt Chief Minister during a live interview, accepting a brazen dare to govern the state for a single day.',
    release_year: 1999,
    genre: 'Action',
    language: 'Tamil',
    duration: '2h 55m',
    director: 'S. Shankar',
    cast_members: 'Arjun Sarja, Manisha Koirala, Raghuvaran, Vadivelu, Vijayakumar',
    poster_url: 'https://images.unsplash.com/photo-1509281373149-e957c6296406?q=80&w=800&auto=format&fit=crop',
    backdrop_url: backdropFallback,
    trailer_url: 'https://www.youtube.com/watch?v=EXeTwQWrcwY',
    featured: false,
    average_rating: 4.8,
    rating_count: 2700,
  },
  {
    title: 'Roja',
    description: 'A young village bride embarks on an agonizing diplomatic journey through the corridors of power to rescue her cryptographer husband kidnapped by militants in Kashmir.',
    release_year: 1992,
    genre: 'Drama',
    language: 'Tamil',
    duration: '2h 17m',
    director: 'Mani Ratnam',
    cast_members: 'Arvind Swamy, Madhoo, Pankaj Kapur, Nassar, Janagaraj',
    poster_url: 'https://images.unsplash.com/photo-1493976040374-85c8e12f0c0e?q=80&w=800&auto=format&fit=crop',
    backdrop_url: backdropFallback,
    trailer_url: 'https://www.youtube.com/watch?v=bLvqoHBptjg',
    featured: false,
    average_rating: 4.8,
    rating_count: 2600,
  },
  {
    title: 'Bombay',
    description: 'An interfaith couple from a coastal Tamil village flees to Bombay to start a life together, only to have their twin sons separated amidst the communal riots of 1992.',
    release_year: 1995,
    genre: 'Drama',
    language: 'Tamil',
    duration: '2h 21m',
    director: 'Mani Ratnam',
    cast_members: 'Arvind Swamy, Manisha Koirala, Nassar, Prakash Raj, Kitty',
    poster_url: 'https://images.unsplash.com/photo-1511671782779-c97d3d27a1d4?q=80&w=800&auto=format&fit=crop',
    backdrop_url: backdropFallback,
    trailer_url: 'https://www.youtube.com/watch?v=sY1S34973zA',
    featured: false,
    average_rating: 4.9,
    rating_count: 2700,
  },
  {
    title: 'Kannathil Muthamittal',
    description: 'An adopted nine-year-old girl in Chennai discovers her biological mother is a rebel soldier caught in the civil war of Sri Lanka and journeys with her parents across battlefields.',
    release_year: 2002,
    genre: 'Drama',
    language: 'Tamil',
    duration: '2h 17m',
    director: 'Mani Ratnam',
    cast_members: 'Madhavan, Simran, P. S. Keerthana, Nandita Das, Prakash Raj',
    poster_url: 'https://images.unsplash.com/photo-1507842229452-976932454b8d?q=80&w=800&auto=format&fit=crop',
    backdrop_url: backdropFallback,
    trailer_url: 'https://www.youtube.com/watch?v=bLvqoHBptjg',
    featured: false,
    average_rating: 4.9,
    rating_count: 2500,
  },
  {
    title: 'Alaipayuthey',
    description: 'A realistic, luminous look at youth romance and the tumultuous transition into early marriage between two passionate lovers who elope against parental opposition.',
    release_year: 2000,
    genre: 'Romance',
    language: 'Tamil',
    duration: '2h 36m',
    director: 'Mani Ratnam',
    cast_members: 'Madhavan, Shalini, Jayasudha, Swarnamalya, Vivek',
    poster_url: 'https://images.unsplash.com/photo-1539037116277-4db20889f2d4?q=80&w=800&auto=format&fit=crop',
    backdrop_url: backdropFallback,
    trailer_url: 'https://www.youtube.com/watch?v=r0f_k_sP9Zk',
    featured: false,
    average_rating: 4.8,
    rating_count: 2700,
  },
  {
    title: 'Vinnaithaandi Varuvaayaa',
    description: 'An aspiring filmmaker falls deeply in love with an older, conservative Christian neighbor in a poignant exploration of timing, heartbreak, and devotion.',
    release_year: 2010,
    genre: 'Romance',
    language: 'Tamil',
    duration: '2h 47m',
    director: 'Gautham Vasudev Menon',
    cast_members: 'Silambarasan TR, Trisha Krishnan, VTV Ganesh, Babu Antony',
    poster_url: 'https://images.unsplash.com/photo-1539037116277-4db20889f2d4?q=80&w=800&auto=format&fit=crop',
    backdrop_url: backdropFallback,
    trailer_url: 'https://www.youtube.com/watch?v=r0f_k_sP9Zk',
    featured: false,
    average_rating: 4.8,
    rating_count: 2800,
  },
  {
    title: 'Vaaranam Aayiram',
    description: 'A grief-stricken NSG commando on a rescue mission reflects on the guiding light of his father, the triumphs of his youth, and healing through tragedy.',
    release_year: 2008,
    genre: 'Drama',
    language: 'Tamil',
    duration: '2h 50m',
    director: 'Gautham Vasudev Menon',
    cast_members: 'Suriya, Simran, Sameera Reddy, Divya Spandana',
    poster_url: 'https://images.unsplash.com/photo-1493976040374-85c8e12f0c0e?q=80&w=800&auto=format&fit=crop',
    backdrop_url: backdropFallback,
    trailer_url: 'https://www.youtube.com/watch?v=bLvqoHBptjg',
    featured: false,
    average_rating: 4.8,
    rating_count: 2900,
  },
  {
    title: 'Kaakha Kaakha',
    description: 'An encounter specialist in the Chennai police force finds warmth in love with a schoolteacher before a vengeful drug lord vows to eradicate everyone he holds dear.',
    release_year: 2003,
    genre: 'Action',
    language: 'Tamil',
    duration: '2h 33m',
    director: 'Gautham Vasudev Menon',
    cast_members: 'Suriya, Jyothika, Jeevan, Daniel Balaji',
    poster_url: 'https://images.unsplash.com/photo-1517604931442-7e0c8ed2963c?q=80&w=800&auto=format&fit=crop',
    backdrop_url: backdropFallback,
    trailer_url: 'https://www.youtube.com/watch?v=EXeTwQWrcwY',
    featured: false,
    average_rating: 4.8,
    rating_count: 2500,
  },
  {
    title: 'Pudhupettai',
    description: 'An impoverished teenager escapes home after witnessing domestic violence and ascends into the grim, cutthroat arena of gang politics in northern Chennai.',
    release_year: 2006,
    genre: 'Crime',
    language: 'Tamil',
    duration: '2h 48m',
    director: 'Selvaraghavan',
    cast_members: 'Dhanush, Sonia Agarwal, Sneha, Vijay Sethupathi',
    poster_url: 'https://images.unsplash.com/photo-1518173946687-a4c8a383392e?q=80&w=800&auto=format&fit=crop',
    backdrop_url: backdropFallback,
    trailer_url: 'https://www.youtube.com/watch?v=znmZoVkCjpI',
    featured: false,
    average_rating: 4.8,
    rating_count: 2700,
  },
  {
    title: 'Aayirathil Oruvan',
    description: 'An archeological expedition into uncharted Vietnamese waters uncovers an ancient, surviving enclave of the Chola empire guarding mystical legacies.',
    release_year: 2010,
    genre: 'Adventure',
    language: 'Tamil',
    duration: '3h 01m',
    director: 'Selvaraghavan',
    cast_members: 'Karthi, Reemma Sen, Andrea Jeremiah, Parthiban',
    poster_url: 'https://images.unsplash.com/photo-1448375240586-882707db888b?q=80&w=800&auto=format&fit=crop',
    backdrop_url: backdropFallback,
    trailer_url: 'https://www.youtube.com/watch?v=D4qAQYLGZVM',
    featured: false,
    average_rating: 4.7,
    rating_count: 2400,
  },
  {
    title: 'Jigarthanda',
    description: 'An ambitious aspiring filmmaker secretly trails a terrifying, bloodthirsty Madurai gangster to pen a film script, resulting in chaotic role reversals.',
    release_year: 2014,
    genre: 'Crime',
    language: 'Tamil',
    duration: '2h 51m',
    director: 'Karthik Subbaraj',
    cast_members: 'Siddharth, Bobby Simha, Lakshmi Menon, Karunakaran',
    poster_url: 'https://images.unsplash.com/photo-1594909122845-11baa439b7bf?q=80&w=800&auto=format&fit=crop',
    backdrop_url: backdropFallback,
    trailer_url: 'https://www.youtube.com/watch?v=s7EdQ4FqbhY',
    featured: true,
    average_rating: 4.8,
    rating_count: 2800,
  },
  {
    title: 'Jigarthanda DoubleX',
    description: 'Set in 1975, an undercover cop posing as a Satyajit Ray disciple directs a ruthless forest dacoit in a groundbreaking Western that transforms tribal liberation.',
    release_year: 2023,
    genre: 'Action',
    language: 'Tamil',
    duration: '2h 52m',
    director: 'Karthik Subbaraj',
    cast_members: 'Raghava Lawrence, S. J. Suryah, Nimisha Sajayan, Shine Tom Chacko',
    poster_url: 'https://images.unsplash.com/photo-1518709268805-4e9042af9f23?q=80&w=800&auto=format&fit=crop',
    backdrop_url: backdropFallback,
    trailer_url: 'https://www.youtube.com/watch?v=s7EdQ4FqbhY',
    featured: false,
    average_rating: 4.8,
    rating_count: 2600,
  },
  {
    title: 'Pizza',
    description: 'A pizza delivery boy who scoffs at the supernatural finds himself locked inside a client haunted mansion with bizarre apparitions during a delivery.',
    release_year: 2012,
    genre: 'Horror',
    language: 'Tamil',
    duration: '2h 08m',
    director: 'Karthik Subbaraj',
    cast_members: 'Vijay Sethupathi, Remya Nambeesan, Aadukalam Naren, Karunakaran',
    poster_url: 'https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?q=80&w=800&auto=format&fit=crop',
    backdrop_url: backdropFallback,
    trailer_url: 'https://www.youtube.com/watch?v=znmZoVkCjpI',
    featured: false,
    average_rating: 4.7,
    rating_count: 2400,
  },
  {
    title: 'Petta',
    description: 'A charming, high-spirited college hostel warden with an intimidating past stands up to local thugs, igniting a war with a notorious Uttar Pradesh politician.',
    release_year: 2019,
    genre: 'Action',
    language: 'Tamil',
    duration: '2h 51m',
    director: 'Karthik Subbaraj',
    cast_members: 'Superstar Rajinikanth, Vijay Sethupathi, Nawazuddin Siddiqui, Simran, Trisha',
    poster_url: 'https://images.unsplash.com/photo-1509281373149-e957c6296406?q=80&w=800&auto=format&fit=crop',
    backdrop_url: backdropFallback,
    trailer_url: 'https://www.youtube.com/watch?v=EXeTwQWrcwY',
    featured: false,
    average_rating: 4.7,
    rating_count: 3100,
  },
  {
    title: 'Aadukalam',
    description: 'In the rooster-fighting arenas of Madurai, an innocent protégé is betrayed by his jealous mentor when his prize rooster wins against insurmountable odds.',
    release_year: 2011,
    genre: 'Drama',
    language: 'Tamil',
    duration: '2h 40m',
    director: 'Vetrimaaran',
    cast_members: 'Dhanush, Taapsee Pannu, V. I. S. Jayapalan, Kishore',
    poster_url: 'https://images.unsplash.com/photo-1518173946687-a4c8a383392e?q=80&w=800&auto=format&fit=crop',
    backdrop_url: backdropFallback,
    trailer_url: 'https://www.youtube.com/watch?v=bLvqoHBptjg',
    featured: false,
    average_rating: 4.9,
    rating_count: 2800,
  },
  {
    title: 'Polladhavan',
    description: 'A jobless youth pride and joy—his newly acquired motorcycle—is stolen by drug peddlers, dragging him into the lethal web of Chennai narcotics kingpins.',
    release_year: 2007,
    genre: 'Action',
    language: 'Tamil',
    duration: '2h 30m',
    director: 'Vetrimaaran',
    cast_members: 'Dhanush, Divya Spandana, Daniel Balaji, Kishore, Santhanam',
    poster_url: 'https://images.unsplash.com/photo-1542751371-adc38448a05e?q=80&w=800&auto=format&fit=crop',
    backdrop_url: backdropFallback,
    trailer_url: 'https://www.youtube.com/watch?v=UTiXQcrLnv4',
    featured: false,
    average_rating: 4.8,
    rating_count: 2600,
  },
  {
    title: 'Visaranai',
    description: 'Four immigrant Tamil laborers in Andhra Pradesh are framed for a high-profile robbery and subjected to brutal custodial torture in an indictment of systemic power.',
    release_year: 2015,
    genre: 'Crime',
    language: 'Tamil',
    duration: '1h 58m',
    director: 'Vetrimaaran',
    cast_members: 'Dinesh, Anandhi, Samuthirakani, Kishore, Murugadoss',
    poster_url: 'https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?q=80&w=800&auto=format&fit=crop',
    backdrop_url: backdropFallback,
    trailer_url: 'https://www.youtube.com/watch?v=znmZoVkCjpI',
    featured: false,
    average_rating: 4.9,
    rating_count: 2500,
  },
  {
    title: 'Viduthalai Part 1',
    description: 'A newly recruited idealistic police constable stationed at an armed hill outpost is torn between orders and conscience during an operation against a separatist leader.',
    release_year: 2023,
    genre: 'Drama',
    language: 'Tamil',
    duration: '2h 30m',
    director: 'Vetrimaaran',
    cast_members: 'Soori, Vijay Sethupathi, Bhavani Sre, Gautham Vasudev Menon',
    poster_url: 'https://images.unsplash.com/photo-1507842229452-976932454b8d?q=80&w=800&auto=format&fit=crop',
    backdrop_url: backdropFallback,
    trailer_url: 'https://www.youtube.com/watch?v=bLvqoHBptjg',
    featured: true,
    average_rating: 4.8,
    rating_count: 2700,
  },
  {
    title: 'Vikram Vedha',
    description: 'A righteous encounter specialist police officer engages in a relentless game of cat-and-mouse with a charming smuggler who challenges his notions of absolute justice.',
    release_year: 2017,
    genre: 'Action',
    language: 'Tamil',
    duration: '2h 27m',
    director: 'Pushkar–Gayathri',
    cast_members: 'R. Madhavan, Vijay Sethupathi, Shraddha Srinath, Varalaxmi Sarathkumar',
    poster_url: 'https://images.unsplash.com/photo-1517604931442-7e0c8ed2963c?q=80&w=800&auto=format&fit=crop',
    backdrop_url: backdropFallback,
    trailer_url: 'https://www.youtube.com/watch?v=1sNrC7_G1S0',
    featured: true,
    average_rating: 4.9,
    rating_count: 3400,
  },
  {
    title: 'Aruvi',
    description: 'A gentle, free-spirited young woman diagnosed with HIV navigates a hypocritical society and commercial television trial that misunderstands her truth.',
    release_year: 2017,
    genre: 'Drama',
    language: 'Tamil',
    duration: '2h 10m',
    director: 'Arun Prabu Purushothaman',
    cast_members: 'Aditi Balan, Anjali Varathan, Lakshmi Gopalswamy, Pradeep Anthony',
    poster_url: 'https://images.unsplash.com/photo-1511671782779-c97d3d27a1d4?q=80&w=800&auto=format&fit=crop',
    backdrop_url: backdropFallback,
    trailer_url: 'https://www.youtube.com/watch?v=bLvqoHBptjg',
    featured: false,
    average_rating: 4.8,
    rating_count: 2200,
  },
  {
    title: 'Maanagaram',
    description: 'Four disparate individuals navigate the sprawling, unfeeling metropolis of Chennai as their paths collide during a bungled extortion kidnapping.',
    release_year: 2017,
    genre: 'Thriller',
    language: 'Tamil',
    duration: '2h 17m',
    director: 'Lokesh Kanagaraj',
    cast_members: 'Sundeep Kishan, Sri, Regina Cassandra, Charle, Ramdoss',
    poster_url: 'https://images.unsplash.com/photo-1542751371-adc38448a05e?q=80&w=800&auto=format&fit=crop',
    backdrop_url: backdropFallback,
    trailer_url: 'https://www.youtube.com/watch?v=znmZoVkCjpI',
    featured: false,
    average_rating: 4.8,
    rating_count: 2300,
  },
  {
    title: 'Doctor',
    description: 'A stoic, hyper-calculating military surgeon teams up with an eccentric family to dismantle an international human trafficking syndicate that abducted his niece.',
    release_year: 2021,
    genre: 'Action',
    language: 'Tamil',
    duration: '2h 28m',
    director: 'Nelson Dilipkumar',
    cast_members: 'Sivakarthikeyan, Vinay Rai, Priyanka Arul Mohan, Yogi Babu, Redin Kingsley',
    poster_url: 'https://images.unsplash.com/photo-1517154421773-0529f29ea451?q=80&w=800&auto=format&fit=crop',
    backdrop_url: backdropFallback,
    trailer_url: 'https://www.youtube.com/watch?v=UTiXQcrLnv4',
    featured: false,
    average_rating: 4.7,
    rating_count: 2700,
  },
  {
    title: 'Amaran',
    description: 'The biographical military epic of Major Mukund Varadarajan, Ashok Chakra recipient, who led the 44th Rashtriya Rifles in counter-insurgency operations in Shopian, Kashmir.',
    release_year: 2024,
    genre: 'Action',
    language: 'Tamil',
    duration: '2h 49m',
    director: 'Rajkumar Periasamy',
    cast_members: 'Sivakarthikeyan, Sai Pallavi, Bhuvan Arora, Rahul Bose',
    poster_url: 'https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?q=80&w=800&auto=format&fit=crop',
    backdrop_url: backdropFallback,
    trailer_url: 'https://www.youtube.com/watch?v=EXeTwQWrcwY',
    featured: true,
    average_rating: 4.9,
    rating_count: 3600,
  },
  {
    title: 'Raayan',
    description: 'A protective elder brother who runs a humble fast-food stall in north Chennai unleashes ferocious retribution when gang rivalries endanger his siblings.',
    release_year: 2024,
    genre: 'Action',
    language: 'Tamil',
    duration: '2h 25m',
    director: 'Dhanush',
    cast_members: 'Dhanush, S. J. Suryah, Sundeep Kishan, Kalidas Jayaram, Dushara Vijayan',
    poster_url: 'https://images.unsplash.com/photo-1509281373149-e957c6296406?q=80&w=800&auto=format&fit=crop',
    backdrop_url: backdropFallback,
    trailer_url: 'https://www.youtube.com/watch?v=s7EdQ4FqbhY',
    featured: true,
    average_rating: 4.7,
    rating_count: 3200,
  },
  {
    title: 'The Greatest of All Time (GOAT)',
    description: 'An elite special antiterrorist squad operative confronts a rogue clone of his past created through genetic manipulation and vengeful syndicate leaders.',
    release_year: 2024,
    genre: 'Action',
    language: 'Tamil',
    duration: '3h 03m',
    director: 'Venkat Prabhu',
    cast_members: 'Thalapathy Vijay, Prashanth, Prabhu Deva, Sneha, Meenakshi Chaudhary',
    poster_url: 'https://images.unsplash.com/photo-1542751371-adc38448a05e?q=80&w=800&auto=format&fit=crop',
    backdrop_url: backdropFallback,
    trailer_url: 'https://www.youtube.com/watch?v=UTiXQcrLnv4',
    featured: true,
    average_rating: 4.7,
    rating_count: 3600,
  },
  {
    title: 'Thangalaan',
    description: 'Set during British colonial rule in Kolar Gold Fields, an indomitable tribal chieftain leads his people against a mythical guardian sorceress and colonial exploiters.',
    release_year: 2024,
    genre: 'Action',
    language: 'Tamil',
    duration: '2h 36m',
    director: 'Pa. Ranjith',
    cast_members: 'Chiyaan Vikram, Malavika Mohanan, Parvathy Thiruvothu, Pasupathy',
    poster_url: 'https://images.unsplash.com/photo-1518709268805-4e9042af9f23?q=80&w=800&auto=format&fit=crop',
    backdrop_url: backdropFallback,
    trailer_url: 'https://www.youtube.com/watch?v=D4qAQYLGZVM',
    featured: true,
    average_rating: 4.8,
    rating_count: 2900,
  },
  {
    title: 'Meiyazhagan',
    description: 'A gentle, melancholic man returns to his ancestral village after 22 years for a cousin wedding, rediscovering pure kinship through an unconditionally loving relative.',
    release_year: 2024,
    genre: 'Drama',
    language: 'Tamil',
    duration: '2h 57m',
    director: 'C. Prem Kumar',
    cast_members: 'Karthi, Arvind Swamy, Sri Divya, Rajkiran, Devadarshini',
    poster_url: 'https://images.unsplash.com/photo-1493976040374-85c8e12f0c0e?q=80&w=800&auto=format&fit=crop',
    backdrop_url: backdropFallback,
    trailer_url: 'https://www.youtube.com/watch?v=r0f_k_sP9Zk',
    featured: true,
    average_rating: 4.9,
    rating_count: 3100,
  },
  {
    title: 'Kottukkaali',
    description: 'A young rebellious woman who fell in love with an oppressed caste youth is forced on an arduous pilgrimage by her patriarchal family to exorcise her love.',
    release_year: 2024,
    genre: 'Drama',
    language: 'Tamil',
    duration: '1h 40m',
    director: 'P. S. Vinothraj',
    cast_members: 'Soori, Anna Ben',
    poster_url: 'https://images.unsplash.com/photo-1507842229452-976932454b8d?q=80&w=800&auto=format&fit=crop',
    backdrop_url: backdropFallback,
    trailer_url: 'https://www.youtube.com/watch?v=bLvqoHBptjg',
    featured: false,
    average_rating: 4.8,
    rating_count: 1900,
  },
  {
    title: 'Kadaisi Vivasayi',
    description: 'An octogenarian traditional farmer, the sole remaining cultivator in his arid village, faces judicial absurdity when framed for killing peafowl.',
    release_year: 2021,
    genre: 'Drama',
    language: 'Tamil',
    duration: '2h 22m',
    director: 'M. Manikandan',
    cast_members: 'Nallandi, Vijay Sethupathi, Yogi Babu, Muneeshwaran',
    poster_url: 'https://images.unsplash.com/photo-1511671782779-c97d3d27a1d4?q=80&w=800&auto=format&fit=crop',
    backdrop_url: backdropFallback,
    trailer_url: 'https://www.youtube.com/watch?v=bLvqoHBptjg',
    featured: false,
    average_rating: 4.9,
    rating_count: 2200,
  },
  {
    title: 'Gargi',
    description: 'A humble schoolteacher embarks on an agonizing judicial crusade to defend her elderly father who was arrested in a horrific child abuse crime.',
    release_year: 2022,
    genre: 'Drama',
    language: 'Tamil',
    duration: '2h 19m',
    director: 'Gautham Ramachandran',
    cast_members: 'Sai Pallavi, Kaali Venkat, R. S. Shivaji, Saravanan',
    poster_url: 'https://images.unsplash.com/photo-1493976040374-85c8e12f0c0e?q=80&w=800&auto=format&fit=crop',
    backdrop_url: backdropFallback,
    trailer_url: 'https://www.youtube.com/watch?v=bLvqoHBptjg',
    featured: false,
    average_rating: 4.9,
    rating_count: 2300,
  },
  {
    title: 'Mandela',
    description: 'During local civic panchayat elections tied between two feuding castes, an impoverished village barber single newly issued vote becomes the kingmaker.',
    release_year: 2021,
    genre: 'Comedy',
    language: 'Tamil',
    duration: '2h 20m',
    director: 'Madonne Ashwin',
    cast_members: 'Yogi Babu, Sheela Rajkumar, Sangili Murugan, G. M. Sundar',
    poster_url: 'https://images.unsplash.com/photo-1536440136628-849c177e76a1?q=80&w=800&auto=format&fit=crop',
    backdrop_url: backdropFallback,
    trailer_url: 'https://www.youtube.com/watch?v=bLvqoHBptjg',
    featured: false,
    average_rating: 4.8,
    rating_count: 2400,
  },
  {
    title: 'Kaaka Muttai',
    description: 'Two slum boys from Chennai embark on an entrepreneurial quest to earn 300 rupees to taste a slice from a newly opened neighborhood pizza parlor.',
    release_year: 2014,
    genre: 'Drama',
    language: 'Tamil',
    duration: '1h 49m',
    director: 'M. Manikandan',
    cast_members: 'Vignesh, Ramesh, Iyshwarya Rajesh, Ramesh Thilak',
    poster_url: 'https://images.unsplash.com/photo-1507842229452-976932454b8d?q=80&w=800&auto=format&fit=crop',
    backdrop_url: backdropFallback,
    trailer_url: 'https://www.youtube.com/watch?v=bLvqoHBptjg',
    featured: false,
    average_rating: 4.9,
    rating_count: 2600,
  },
  {
    title: 'Thevar Magan',
    description: 'A Western-educated young man returns home aspiring to open restaurants, but is thrust into ancestral responsibilities when violent clan rivalries erupt.',
    release_year: 1992,
    genre: 'Drama',
    language: 'Tamil',
    duration: '2h 25m',
    director: 'Bharathan',
    cast_members: 'Sivaji Ganesan, Kamal Haasan, Revathi, Gautami, Nassar',
    poster_url: 'https://images.unsplash.com/photo-1518173946687-a4c8a383392e?q=80&w=800&auto=format&fit=crop',
    backdrop_url: backdropFallback,
    trailer_url: 'https://www.youtube.com/watch?v=sY1S34973zA',
    featured: true,
    average_rating: 4.9,
    rating_count: 3100,
  },
  {
    title: 'Hey Ram',
    description: 'A grieving archaeologist in Calcutta radicalizes amidst Partition riots and plots to assassinate Mahatma Gandhi before experiencing transformative redemption.',
    release_year: 2000,
    genre: 'Drama',
    language: 'Tamil',
    duration: '3h 30m',
    director: 'Kamal Haasan',
    cast_members: 'Kamal Haasan, Shah Rukh Khan, Rani Mukerji, Hema Malini, Nassar',
    poster_url: 'https://images.unsplash.com/photo-1506703719100-a0f3a48c0f86?q=80&w=800&auto=format&fit=crop',
    backdrop_url: backdropFallback,
    trailer_url: 'https://www.youtube.com/watch?v=sY1S34973zA',
    featured: true,
    average_rating: 4.9,
    rating_count: 2800,
  },
  {
    title: 'Virumaandi',
    description: 'Told through Rashomon-style perspectives of two death-row inmates, an innocent village bull-tamer recounts how clan vendettas framed him for slaughter.',
    release_year: 2004,
    genre: 'Action',
    language: 'Tamil',
    duration: '2h 58m',
    director: 'Kamal Haasan',
    cast_members: 'Kamal Haasan, Abhirami, Pasupathy, Napoleon, Rohini',
    poster_url: 'https://images.unsplash.com/photo-1517604931442-7e0c8ed2963c?q=80&w=800&auto=format&fit=crop',
    backdrop_url: backdropFallback,
    trailer_url: 'https://www.youtube.com/watch?v=s7EdQ4FqbhY',
    featured: false,
    average_rating: 4.9,
    rating_count: 2700,
  },
  {
    title: 'Apoorva Sagodharargal',
    description: 'Separated twin brothers—one an agile circus clown of short stature and the other a mechanic—exact ingenious revenge against the killers of their police father.',
    release_year: 1989,
    genre: 'Comedy',
    language: 'Tamil',
    duration: '2h 36m',
    director: 'Singeetam Srinivasa Rao',
    cast_members: 'Kamal Haasan, Gautami, Rupini, Jaishankar, Nagesh',
    poster_url: 'https://images.unsplash.com/photo-1536440136628-849c177e76a1?q=80&w=800&auto=format&fit=crop',
    backdrop_url: backdropFallback,
    trailer_url: 'https://www.youtube.com/watch?v=sY1S34973zA',
    featured: false,
    average_rating: 4.9,
    rating_count: 2900,
  },
  {
    title: 'Moondram Pirai',
    description: 'A compassionate schoolteacher in Ooty shelters and rehabilitates an amnesiac woman with child-like mental faculty, culminating in one of cinema most heartbreaking farewells.',
    release_year: 1982,
    genre: 'Drama',
    language: 'Tamil',
    duration: '2h 22m',
    director: 'Balu Mahendra',
    cast_members: 'Kamal Haasan, Sridevi, Silk Smitha, Y. G. Mahendran',
    poster_url: 'https://images.unsplash.com/photo-1511671782779-c97d3d27a1d4?q=80&w=800&auto=format&fit=crop',
    backdrop_url: backdropFallback,
    trailer_url: 'https://www.youtube.com/watch?v=bLvqoHBptjg',
    featured: true,
    average_rating: 4.9,
    rating_count: 2800,
  },
  {
    title: 'Padayappa',
    description: 'An honorable mechanical engineer battles family betrayals and the lifelong, scornful vendetta of an arrogant heiress whose marriage proposal he rejected.',
    release_year: 1999,
    genre: 'Action',
    language: 'Tamil',
    duration: '2h 59m',
    director: 'K. S. Ravikumar',
    cast_members: 'Superstar Rajinikanth, Ramya Krishnan, Soundarya, Sivaji Ganesan, Abbas',
    poster_url: 'https://images.unsplash.com/photo-1509281373149-e957c6296406?q=80&w=800&auto=format&fit=crop',
    backdrop_url: backdropFallback,
    trailer_url: 'https://www.youtube.com/watch?v=EXeTwQWrcwY',
    featured: true,
    average_rating: 4.9,
    rating_count: 3500,
  },
  {
    title: 'Chandramukhi',
    description: 'A top psychiatrist uncovers the psychological trauma and dissociative possession of a newlywed bride residing inside an ancient, haunted palace.',
    release_year: 2005,
    genre: 'Horror',
    language: 'Tamil',
    duration: '2h 46m',
    director: 'P. Vasu',
    cast_members: 'Superstar Rajinikanth, Jyothika, Prabhu, Nayanthara, Vadivelu',
    poster_url: 'https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?q=80&w=800&auto=format&fit=crop',
    backdrop_url: backdropFallback,
    trailer_url: 'https://www.youtube.com/watch?v=znmZoVkCjpI',
    featured: false,
    average_rating: 4.8,
    rating_count: 3200,
  },
  {
    title: 'Kabali',
    description: 'An aged Malaysian Tamil underworld don is released from prison after 25 years and embarks on a crusade to reunite with his family while battling predatory triads.',
    release_year: 2016,
    genre: 'Action',
    language: 'Tamil',
    duration: '2h 33m',
    director: 'Pa. Ranjith',
    cast_members: 'Superstar Rajinikanth, Radhika Apte, Winston Chao, Sai Dhanshika',
    poster_url: 'https://images.unsplash.com/photo-1518173946687-a4c8a383392e?q=80&w=800&auto=format&fit=crop',
    backdrop_url: backdropFallback,
    trailer_url: 'https://www.youtube.com/watch?v=9mdJV5-eias',
    featured: false,
    average_rating: 4.6,
    rating_count: 3100,
  },
  {
    title: 'Kaala',
    description: 'The righteous patriarch of Dharavi slum in Mumbai mobilizes his community against a predatory land baron and union minister bent on cleansing the settlement.',
    release_year: 2018,
    genre: 'Action',
    language: 'Tamil',
    duration: '2h 46m',
    director: 'Pa. Ranjith',
    cast_members: 'Superstar Rajinikanth, Nana Patekar, Samuthirakani, Eswari Rao, Huma Qureshi',
    poster_url: 'https://images.unsplash.com/photo-1509281373149-e957c6296406?q=80&w=800&auto=format&fit=crop',
    backdrop_url: backdropFallback,
    trailer_url: 'https://www.youtube.com/watch?v=Wm_vSSlBsV8',
    featured: false,
    average_rating: 4.7,
    rating_count: 2900,
  },
  {
    title: 'Maanaadu',
    description: 'A young man attending a political conference finds himself trapped in a time loop on the day of the Chief Minister assassination and must prevent disaster.',
    release_year: 2021,
    genre: 'Sci-Fi',
    language: 'Tamil',
    duration: '2h 27m',
    director: 'Venkat Prabhu',
    cast_members: 'Silambarasan TR, S. J. Suryah, Kalyani Priyadarshan, S. A. Chandrasekhar',
    poster_url: 'https://images.unsplash.com/photo-1542751371-adc38448a05e?q=80&w=800&auto=format&fit=crop',
    backdrop_url: backdropFallback,
    trailer_url: 'https://www.youtube.com/watch?v=t9h_6W-8i7A',
    featured: true,
    average_rating: 4.8,
    rating_count: 3200,
  },
  {
    title: 'Thani Oruvan',
    description: 'An upright police IPS trainee covertly investigates a web of high-profile financial and medical crimes, pinpointing an amoral scientist mastermind as his nemesis.',
    release_year: 2015,
    genre: 'Thriller',
    language: 'Tamil',
    duration: '2h 40m',
    director: 'Mohan Raja',
    cast_members: 'Jayam Ravi, Arvind Swamy, Nayanthara, Thambi Ramaiah, Ganesh Venkatraman',
    poster_url: 'https://images.unsplash.com/photo-1507842229452-976932454b8d?q=80&w=800&auto=format&fit=crop',
    backdrop_url: backdropFallback,
    trailer_url: 'https://www.youtube.com/watch?v=r5L_bA67vXk',
    featured: true,
    average_rating: 4.9,
    rating_count: 3100,
  },
  {
    title: 'I',
    description: 'A gentle bodybuilder crowned Mr. Tamil Nadu is systematically disfigured with a viral poison by envious rivals and uses his vengeance to punish them.',
    release_year: 2015,
    genre: 'Action',
    language: 'Tamil',
    duration: '3h 08m',
    director: 'S. Shankar',
    cast_members: 'Chiyaan Vikram, Amy Jackson, Suresh Gopi, Santhanam, Upen Patel',
    poster_url: 'https://images.unsplash.com/photo-1518709268805-4e9042af9f23?q=80&w=800&auto=format&fit=crop',
    backdrop_url: backdropFallback,
    trailer_url: 'https://www.youtube.com/watch?v=s7EdQ4FqbhY',
    featured: false,
    average_rating: 4.7,
    rating_count: 2900,
  },
  {
    title: 'Deiva Thirumagal',
    description: 'An intellectually disabled father with the emotional maturity of a seven-year-old fights a custody battle against his wealthy father-in-law for his beloved daughter.',
    release_year: 2011,
    genre: 'Drama',
    language: 'Tamil',
    duration: '2h 46m',
    director: 'A. L. Vijay',
    cast_members: 'Chiyaan Vikram, Baby Sarah, Anushka Shetty, Amala Paul, Nassar',
    poster_url: 'https://images.unsplash.com/photo-1493976040374-85c8e12f0c0e?q=80&w=800&auto=format&fit=crop',
    backdrop_url: backdropFallback,
    trailer_url: 'https://www.youtube.com/watch?v=bLvqoHBptjg',
    featured: false,
    average_rating: 4.8,
    rating_count: 2700,
  },
  {
    title: '24',
    description: 'A watchmaker inherits a mysterious watch invented by his late scientist father that allows the wearer to travel back up to 24 hours in time, drawing the wrath of an evil uncle.',
    release_year: 2016,
    genre: 'Sci-Fi',
    language: 'Tamil',
    duration: '2h 44m',
    director: 'Vikram Kumar',
    cast_members: 'Suriya, Samantha Ruth Prabhu, Nithya Menen, Saranya Ponvannan',
    poster_url: 'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?q=80&w=800&auto=format&fit=crop',
    backdrop_url: backdropFallback,
    trailer_url: 'https://www.youtube.com/watch?v=0k57_jW4A7Y',
    featured: true,
    average_rating: 4.8,
    rating_count: 3100,
  },
  {
    title: 'Ghajini',
    description: 'A wealthy telecom executive suffering from anterograde amnesia uses Polaroid photographs and body tattoos to hunt down the syndicate that murdered his beloved.',
    release_year: 2005,
    genre: 'Action',
    language: 'Tamil',
    duration: '2h 55m',
    director: 'AR Murugadoss',
    cast_members: 'Suriya, Asin, Nayanthara, Pradeep Rawat, Riyaz Khan',
    poster_url: 'https://images.unsplash.com/photo-1517604931442-7e0c8ed2963c?q=80&w=800&auto=format&fit=crop',
    backdrop_url: backdropFallback,
    trailer_url: 'https://www.youtube.com/watch?v=EXeTwQWrcwY',
    featured: true,
    average_rating: 4.8,
    rating_count: 3300,
  },
  {
    title: '7aum Arivu',
    description: 'A genetic scientist and a circus acrobat descendant of 6th-century monk Bodhidharma attempt to revive ancient martial memories to thwart a biological weapon.',
    release_year: 2011,
    genre: 'Sci-Fi',
    language: 'Tamil',
    duration: '2h 48m',
    director: 'AR Murugadoss',
    cast_members: 'Suriya, Shruti Haasan, Johnny Tri Nguyen, Avinash',
    poster_url: 'https://images.unsplash.com/photo-1542751371-adc38448a05e?q=80&w=800&auto=format&fit=crop',
    backdrop_url: backdropFallback,
    trailer_url: 'https://www.youtube.com/watch?v=vKQi3bBA1y8',
    featured: false,
    average_rating: 4.6,
    rating_count: 2600,
  },
  {
    title: 'Mersal',
    description: 'A magician and an overseas doctor uncover corruption and extortion in India healthcare system while seeking vengeance for the murder of their parents.',
    release_year: 2017,
    genre: 'Action',
    language: 'Tamil',
    duration: '2h 52m',
    director: 'Atlee',
    cast_members: 'Thalapathy Vijay, S. J. Suryah, Nithya Menen, Samantha, Kajal Aggarwal',
    poster_url: 'https://images.unsplash.com/photo-1509281373149-e957c6296406?q=80&w=800&auto=format&fit=crop',
    backdrop_url: backdropFallback,
    trailer_url: 'https://www.youtube.com/watch?v=gQqbcswbRe8',
    featured: true,
    average_rating: 4.8,
    rating_count: 3600,
  },
  {
    title: 'Bigil',
    description: 'A former football prodigy turned slum savior agrees to coach a women state football team to honor his late father vision and challenge discrimination.',
    release_year: 2019,
    genre: 'Action',
    language: 'Tamil',
    duration: '2h 59m',
    director: 'Atlee',
    cast_members: 'Thalapathy Vijay, Nayanthara, Jackie Shroff, Vivek, Kathir',
    poster_url: 'https://images.unsplash.com/photo-1517154421773-0529f29ea451?q=80&w=800&auto=format&fit=crop',
    backdrop_url: backdropFallback,
    trailer_url: 'https://www.youtube.com/watch?v=UTiXQcrLnv4',
    featured: false,
    average_rating: 4.7,
    rating_count: 3400,
  },
  {
    title: 'Theri',
    description: 'A former DCP who staged his own death to raise his daughter in peace is forced to revive his violent past when a vile politician seeks revenge.',
    release_year: 2016,
    genre: 'Action',
    language: 'Tamil',
    duration: '2h 38m',
    director: 'Atlee',
    cast_members: 'Thalapathy Vijay, Samantha Ruth Prabhu, Amy Jackson, Nainika, J. Mahendran',
    poster_url: 'https://images.unsplash.com/photo-1509281373149-e957c6296406?q=80&w=800&auto=format&fit=crop',
    backdrop_url: backdropFallback,
    trailer_url: 'https://www.youtube.com/watch?v=EXeTwQWrcwY',
    featured: false,
    average_rating: 4.7,
    rating_count: 3200,
  },
  {
    title: 'Vedalam',
    description: 'A seemingly timid taxi driver in Kolkata conceals an intimidating, merciless vigilante past to shield his foster sister from international traffickers.',
    release_year: 2015,
    genre: 'Action',
    language: 'Tamil',
    duration: '2h 32m',
    director: 'Siva',
    cast_members: 'Ajith Kumar, Shruti Haasan, Lakshmi Menon, Rahul Dev, Soori',
    poster_url: 'https://images.unsplash.com/photo-1542751371-adc38448a05e?q=80&w=800&auto=format&fit=crop',
    backdrop_url: backdropFallback,
    trailer_url: 'https://www.youtube.com/watch?v=UTiXQcrLnv4',
    featured: false,
    average_rating: 4.7,
    rating_count: 2800,
  },
  {
    title: 'Viswasam',
    description: 'A respected village chieftain travels to Mumbai to protect his estranged wife and athlete daughter from a cutthroat pharmaceutical tycoon.',
    release_year: 2019,
    genre: 'Action',
    language: 'Tamil',
    duration: '2h 36m',
    director: 'Siva',
    cast_members: 'Ajith Kumar, Nayanthara, Jagapathi Babu, Vivek, Thambi Ramaiah',
    poster_url: 'https://images.unsplash.com/photo-1518173946687-a4c8a383392e?q=80&w=800&auto=format&fit=crop',
    backdrop_url: backdropFallback,
    trailer_url: 'https://www.youtube.com/watch?v=EXeTwQWrcwY',
    featured: false,
    average_rating: 4.7,
    rating_count: 3000,
  },
  {
    title: 'Valimai',
    description: 'An IPS officer with a penchant for motorcycles battles a syndicate of nihilistic outlaw bikers responsible for violent robberies and drug trafficking.',
    release_year: 2022,
    genre: 'Action',
    language: 'Tamil',
    duration: '2h 58m',
    director: 'H. Vinoth',
    cast_members: 'Ajith Kumar, Huma Qureshi, Kartikeya Gummakonda, Bani J',
    poster_url: 'https://images.unsplash.com/photo-1542751371-adc38448a05e?q=80&w=800&auto=format&fit=crop',
    backdrop_url: backdropFallback,
    trailer_url: 'https://www.youtube.com/watch?v=UTiXQcrLnv4',
    featured: false,
    average_rating: 4.6,
    rating_count: 2800,
  },
  {
    title: 'Nerkonda Paarvai',
    description: 'A retired defense lawyer battling bipolar disorder emerges to defend three courageous women falsely implicated in an assault case by privileged elites.',
    release_year: 2019,
    genre: 'Drama',
    language: 'Tamil',
    duration: '2h 38m',
    director: 'H. Vinoth',
    cast_members: 'Ajith Kumar, Shraddha Srinath, Abhirami Venkatachalam, Andrea Tariang',
    poster_url: 'https://images.unsplash.com/photo-1507842229452-976932454b8d?q=80&w=800&auto=format&fit=crop',
    backdrop_url: backdropFallback,
    trailer_url: 'https://www.youtube.com/watch?v=bLvqoHBptjg',
    featured: false,
    average_rating: 4.8,
    rating_count: 2700,
  },
  {
    title: 'Dhuruvangal Pathinaaru (D-16)',
    description: 'A retired police officer recounts a fateful rainy night and an unsolved hit-and-run investigation that cost him his leg and forever changed three lives.',
    release_year: 2016,
    genre: 'Thriller',
    language: 'Tamil',
    duration: '1h 45m',
    director: 'Karthick Naren',
    cast_members: 'Rahman, Prakash Raghavan, Ashwin Kumar, Anjana Jayaprakash',
    poster_url: 'https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?q=80&w=800&auto=format&fit=crop',
    backdrop_url: backdropFallback,
    trailer_url: 'https://www.youtube.com/watch?v=znmZoVkCjpI',
    featured: false,
    average_rating: 4.8,
    rating_count: 2600,
  },
  {
    title: 'Ayan',
    description: 'An ingenious custom-goods smuggler working for a master kingpin tries to go straight after falling in love, but must first outwit an international cartel.',
    release_year: 2009,
    genre: 'Action',
    language: 'Tamil',
    duration: '2h 42m',
    director: 'K. V. Anand',
    cast_members: 'Suriya, Tamannaah Bhatia, Prabhu, Akashdeep Saighal, Jagan',
    poster_url: 'https://images.unsplash.com/photo-1517604931442-7e0c8ed2963c?q=80&w=800&auto=format&fit=crop',
    backdrop_url: backdropFallback,
    trailer_url: 'https://www.youtube.com/watch?v=EXeTwQWrcwY',
    featured: false,
    average_rating: 4.8,
    rating_count: 3100,
  },
  {
    title: 'Singam',
    description: 'An honorable police sub-inspector from a small coastal town is transferred to Chennai where he locks horns with a ruthless extortionist kidnapper.',
    release_year: 2010,
    genre: 'Action',
    language: 'Tamil',
    duration: '2h 40m',
    director: 'Hari',
    cast_members: 'Suriya, Anushka Shetty, Prakash Raj, Vivek, Radha Ravi',
    poster_url: 'https://images.unsplash.com/photo-1509281373149-e957c6296406?q=80&w=800&auto=format&fit=crop',
    backdrop_url: backdropFallback,
    trailer_url: 'https://www.youtube.com/watch?v=EXeTwQWrcwY',
    featured: false,
    average_rating: 4.8,
    rating_count: 3300,
  },
  {
    title: 'Sethu',
    description: 'A fiery college rogue falls in love with a timid Brahmin girl, but brutal head trauma and a mental asylum threaten their shared destiny.',
    release_year: 1999,
    genre: 'Drama',
    language: 'Tamil',
    duration: '2h 15m',
    director: 'Bala',
    cast_members: 'Chiyaan Vikram, Abitha, Sivakumar, Sriman',
    poster_url: 'https://images.unsplash.com/photo-1493976040374-85c8e12f0c0e?q=80&w=800&auto=format&fit=crop',
    backdrop_url: backdropFallback,
    trailer_url: 'https://www.youtube.com/watch?v=bLvqoHBptjg',
    featured: false,
    average_rating: 4.8,
    rating_count: 2400,
  },
  {
    title: 'Pithamagan',
    description: 'An orphaned gravedigger brought up without human socialization forms an extraordinary, poignant bond with a fast-talking con artist in rural Tamil Nadu.',
    release_year: 2003,
    genre: 'Drama',
    language: 'Tamil',
    duration: '2h 26m',
    director: 'Bala',
    cast_members: 'Chiyaan Vikram, Suriya, Laila, Sangeetha, Simran',
    poster_url: 'https://images.unsplash.com/photo-1518173946687-a4c8a383392e?q=80&w=800&auto=format&fit=crop',
    backdrop_url: backdropFallback,
    trailer_url: 'https://www.youtube.com/watch?v=bLvqoHBptjg',
    featured: true,
    average_rating: 4.9,
    rating_count: 3100,
  },
  {
    title: 'Paruthiveeran',
    description: 'A rugged, carefree rogue in rural Madurai falls for an unyielding village girl who stood by him since childhood, leading to an earth-shattering climax.',
    release_year: 2007,
    genre: 'Drama',
    language: 'Tamil',
    duration: '2h 42m',
    director: 'Ameer',
    cast_members: 'Karthi, Priyamani, Saravanan, Ponvannan, Sujatha Sivakumar',
    poster_url: 'https://images.unsplash.com/photo-1507842229452-976932454b8d?q=80&w=800&auto=format&fit=crop',
    backdrop_url: backdropFallback,
    trailer_url: 'https://www.youtube.com/watch?v=bLvqoHBptjg',
    featured: false,
    average_rating: 4.9,
    rating_count: 2800,
  },
  {
    title: 'Subramaniapuram',
    description: 'In 1980 Madurai, five unemployed loyal friends are manipulated by an ambitious politician into committing a murder that triggers tragic betrayals.',
    release_year: 2008,
    genre: 'Crime',
    language: 'Tamil',
    duration: '2h 17m',
    director: 'M. Sasikumar',
    cast_members: 'Jai, M. Sasikumar, Swathi Reddy, Samuthirakani, Ganja Karuppu',
    poster_url: 'https://images.unsplash.com/photo-1518173946687-a4c8a383392e?q=80&w=800&auto=format&fit=crop',
    backdrop_url: backdropFallback,
    trailer_url: 'https://www.youtube.com/watch?v=znmZoVkCjpI',
    featured: false,
    average_rating: 4.9,
    rating_count: 2900,
  },
  {
    title: 'Madras',
    description: 'A wall in Vyasarpadi, North Chennai, becomes the epicenter of lethal political warfare between two rival factions, trapping an innocent footballer.',
    release_year: 2014,
    genre: 'Action',
    language: 'Tamil',
    duration: '2h 38m',
    director: 'Pa. Ranjith',
    cast_members: 'Karthi, Catherine Tresa, Kalaiyarasan, Riythvika, Charles Vinoth',
    poster_url: 'https://images.unsplash.com/photo-1539037116277-4db20889f2d4?q=80&w=800&auto=format&fit=crop',
    backdrop_url: backdropFallback,
    trailer_url: 'https://www.youtube.com/watch?v=UTiXQcrLnv4',
    featured: false,
    average_rating: 4.8,
    rating_count: 2700,
  },
  {
    title: 'Attakathi',
    description: 'A light-hearted, grounded portrait of a semi-urban youth series of unrequited romantic pursuits through bus rides and college days in Chennai.',
    release_year: 2012,
    genre: 'Comedy',
    language: 'Tamil',
    duration: '2h 17m',
    director: 'Pa. Ranjith',
    cast_members: 'Dinesh, Nandita Swetha, Aishwarya Rajesh, Sophia',
    poster_url: 'https://images.unsplash.com/photo-1536440136628-849c177e76a1?q=80&w=800&auto=format&fit=crop',
    backdrop_url: backdropFallback,
    trailer_url: 'https://www.youtube.com/watch?v=bLvqoHBptjg',
    featured: false,
    average_rating: 4.7,
    rating_count: 2200,
  },
  {
    title: 'Iraivi',
    description: 'Three troubled men in Chennai struggle with toxic masculinity and financial ruin, wreaking unintended emotional havoc on the resilient women in their lives.',
    release_year: 2016,
    genre: 'Drama',
    language: 'Tamil',
    duration: '2h 40m',
    director: 'Karthik Subbaraj',
    cast_members: 'S. J. Suryah, Vijay Sethupathi, Bobby Simha, Anjali, Pooja Devariya',
    poster_url: 'https://images.unsplash.com/photo-1511671782779-c97d3d27a1d4?q=80&w=800&auto=format&fit=crop',
    backdrop_url: backdropFallback,
    trailer_url: 'https://www.youtube.com/watch?v=bLvqoHBptjg',
    featured: false,
    average_rating: 4.8,
    rating_count: 2400,
  },
  {
    title: 'Captain Miller',
    description: 'In 1930s colonial India, a former British Indian Army soldier turns into a legendary rebel outlaw to protect his people ancestral temple treasures.',
    release_year: 2024,
    genre: 'Action',
    language: 'Tamil',
    duration: '2h 37m',
    director: 'Arun Matheswaran',
    cast_members: 'Dhanush, Shiva Rajkumar, Priyanka Arul Mohan, Sundeep Kishan',
    poster_url: 'https://images.unsplash.com/photo-1518709268805-4e9042af9f23?q=80&w=800&auto=format&fit=crop',
    backdrop_url: backdropFallback,
    trailer_url: 'https://www.youtube.com/watch?v=s7EdQ4FqbhY',
    featured: true,
    average_rating: 4.7,
    rating_count: 3100,
  },
  {
    title: 'Ayalaan',
    description: 'A compassionate village youth befriends an eccentric lost extraterrestrial alien and together they fight a greedy industrialist plotting deadly underground mining.',
    release_year: 2024,
    genre: 'Sci-Fi',
    language: 'Tamil',
    duration: '2h 35m',
    director: 'R. Ravikumar',
    cast_members: 'Sivakarthikeyan, Rakul Preet Singh, Sharad Kelkar, Isha Koppikar, Karunakaran',
    poster_url: 'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?q=80&w=800&auto=format&fit=crop',
    backdrop_url: backdropFallback,
    trailer_url: 'https://www.youtube.com/watch?v=0k57_jW4A7Y',
    featured: false,
    average_rating: 4.6,
    rating_count: 2600,
  },
  {
    title: 'Lover',
    description: 'A realistic, intense dissection of a six-year romantic relationship unraveling due to possessiveness, insecurity, and shifting career dynamics.',
    release_year: 2024,
    genre: 'Romance',
    language: 'Tamil',
    duration: '2h 25m',
    director: 'Prabhuram Vyas',
    cast_members: 'K. Manikandan, Sri Gouri Priya, Kanna Ravi, Saravanan',
    poster_url: 'https://images.unsplash.com/photo-1539037116277-4db20889f2d4?q=80&w=800&auto=format&fit=crop',
    backdrop_url: backdropFallback,
    trailer_url: 'https://www.youtube.com/watch?v=r0f_k_sP9Zk',
    featured: false,
    average_rating: 4.7,
    rating_count: 2300,
  },
  {
    title: 'Gunaa',
    description: 'A mentally distressed man abducts a wealthy young woman believing she is his divine reincarnated goddess, leading to a tragic love story in the caves of Kodaikanal.',
    release_year: 1991,
    genre: 'Romance',
    language: 'Tamil',
    duration: '2h 45m',
    director: 'Santhana Bharathi',
    cast_members: 'Kamal Haasan, Roshini, Rekha, Janagaraj, S. P. Balasubrahmanyam',
    poster_url: 'https://images.unsplash.com/photo-1539037116277-4db20889f2d4?q=80&w=800&auto=format&fit=crop',
    backdrop_url: backdropFallback,
    trailer_url: 'https://www.youtube.com/watch?v=bLvqoHBptjg',
    featured: false,
    average_rating: 4.9,
    rating_count: 2700,
  },
  {
    title: 'Mahanadi',
    description: 'An honest widower is swindled into financial catastrophe by con men, imprisoned, and fights desperately to rescue his daughter from a Mumbai brothel.',
    release_year: 1994,
    genre: 'Drama',
    language: 'Tamil',
    duration: '2h 37m',
    director: 'Santhana Bharathi',
    cast_members: 'Kamal Haasan, Sukanya, Cochin Haneefa, Poornam Viswanathan',
    poster_url: 'https://images.unsplash.com/photo-1493976040374-85c8e12f0c0e?q=80&w=800&auto=format&fit=crop',
    backdrop_url: backdropFallback,
    trailer_url: 'https://www.youtube.com/watch?v=bLvqoHBptjg',
    featured: false,
    average_rating: 4.9,
    rating_count: 2600,
  },
  {
    title: 'Dasavathaaram',
    description: 'A bio-scientist races against a rogue CIA mercenary across continents to recover a stolen biological virus, featuring Kamal Haasan in ten distinct legendary roles.',
    release_year: 2008,
    genre: 'Sci-Fi',
    language: 'Tamil',
    duration: '3h 08m',
    director: 'K. S. Ravikumar',
    cast_members: 'Kamal Haasan, Asin, Mallika Sherawat, Jayaprada, Napoleon',
    poster_url: 'https://images.unsplash.com/photo-1542751371-adc38448a05e?q=80&w=800&auto=format&fit=crop',
    backdrop_url: backdropFallback,
    trailer_url: 'https://www.youtube.com/watch?v=vKQi3bBA1y8',
    featured: false,
    average_rating: 4.7,
    rating_count: 3100,
  },
  {
    title: 'Mark Antony',
    description: 'Two estranged sons of 1990s gangsters communicate with their deceased fathers through a temporal telephone to alter the past, causing hilarious and wild temporal paradoxes.',
    release_year: 2023,
    genre: 'Sci-Fi',
    language: 'Tamil',
    duration: '2h 31m',
    director: 'Adhik Ravichandran',
    cast_members: 'Vishal, S. J. Suryah, Ritu Varma, Sunil, Selvaraghavan',
    poster_url: 'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?q=80&w=800&auto=format&fit=crop',
    backdrop_url: backdropFallback,
    trailer_url: 'https://www.youtube.com/watch?v=0k57_jW4A7Y',
    featured: false,
    average_rating: 4.7,
    rating_count: 2900,
  },
  {
    title: 'Billa',
    description: 'When an international Malaysian underworld don is killed in an encounter, an undercover cop recruits a bumbling Chennai lookalike to impersonate him.',
    release_year: 2007,
    genre: 'Action',
    language: 'Tamil',
    duration: '2h 25m',
    director: 'Vishnuvardhan',
    cast_members: 'Ajith Kumar, Nayanthara, Namitha, Prabhu, Rahman',
    poster_url: 'https://images.unsplash.com/photo-1517604931442-7e0c8ed2963c?q=80&w=800&auto=format&fit=crop',
    backdrop_url: backdropFallback,
    trailer_url: 'https://www.youtube.com/watch?v=EXeTwQWrcwY',
    featured: false,
    average_rating: 4.8,
    rating_count: 3100,
  },
  {
    title: 'Velaikkaran',
    description: 'A young man from a slum rises to become a top corporate marketing sales executive, only to discover food adulteration malpractices that harm innocent citizens.',
    release_year: 2017,
    genre: 'Action',
    language: 'Tamil',
    duration: '2h 40m',
    director: 'Mohan Raja',
    cast_members: 'Sivakarthikeyan, Fahadh Faasil, Nayanthara, Sneha, Prakash Raj',
    poster_url: 'https://images.unsplash.com/photo-1509281373149-e957c6296406?q=80&w=800&auto=format&fit=crop',
    backdrop_url: backdropFallback,
    trailer_url: 'https://www.youtube.com/watch?v=UTiXQcrLnv4',
    featured: false,
    average_rating: 4.7,
    rating_count: 2700,
  },
  {
    title: 'Thunivu',
    description: 'A mysterious mastermind known as Darkdevil seizes control of a bank in Chennai during an attempted heist, uncovering an illegal mutual fund scam.',
    release_year: 2023,
    genre: 'Action',
    language: 'Tamil',
    duration: '2h 26m',
    director: 'H. Vinoth',
    cast_members: 'Ajith Kumar, Manju Warrier, Samuthirakani, John Kokken, Pavani Reddy',
    poster_url: 'https://images.unsplash.com/photo-1542751371-adc38448a05e?q=80&w=800&auto=format&fit=crop',
    backdrop_url: backdropFallback,
    trailer_url: 'https://www.youtube.com/watch?v=UTiXQcrLnv4',
    featured: false,
    average_rating: 4.6,
    rating_count: 3100,
  },
  {
    title: 'Beast',
    description: 'An ex-RAW spy visiting a Chennai shopping mall must single-handedly neutralize a terrorist squad that takes hundreds of civilians hostage.',
    release_year: 2022,
    genre: 'Action',
    language: 'Tamil',
    duration: '2h 35m',
    director: 'Nelson Dilipkumar',
    cast_members: 'Thalapathy Vijay, Pooja Hegde, Selvaraghavan, Yogi Babu, Shine Tom Chacko',
    poster_url: 'https://images.unsplash.com/photo-1509281373149-e957c6296406?q=80&w=800&auto=format&fit=crop',
    backdrop_url: backdropFallback,
    trailer_url: 'https://www.youtube.com/watch?v=UTiXQcrLnv4',
    featured: false,
    average_rating: 4.5,
    rating_count: 3400,
  },
  {
    title: 'Vettaiyan',
    description: 'An encounter specialist in the Tamil Nadu police force confronts the ethics of instant justice when an investigation exposes a nationwide educational tech scam.',
    release_year: 2024,
    genre: 'Action',
    language: 'Tamil',
    duration: '2h 43m',
    director: 'T. J. Gnanavel',
    cast_members: 'Superstar Rajinikanth, Amitabh Bachchan, Fahadh Faasil, Rana Daggubati, Manju Warrier',
    poster_url: 'https://images.unsplash.com/photo-1506703719100-a0f3a48c0f86?q=80&w=800&auto=format&fit=crop',
    backdrop_url: backdropFallback,
    trailer_url: 'https://www.youtube.com/watch?v=EXeTwQWrcwY',
    featured: true,
    average_rating: 4.8,
    rating_count: 3700,
  },
  {
    title: 'Kanguva',
    description: 'A dual-timeline epic linking an ancient warlord struggle to protect his island from invaders to a modern-day bounty hunter mission in Goa.',
    release_year: 2024,
    genre: 'Fantasy',
    language: 'Tamil',
    duration: '2h 34m',
    director: 'Siva',
    cast_members: 'Suriya, Bobby Deol, Disha Patani, Yogi Babu, Natarajan Subramaniam',
    poster_url: 'https://images.unsplash.com/photo-1518709268805-4e9042af9f23?q=80&w=800&auto=format&fit=crop',
    backdrop_url: backdropFallback,
    trailer_url: 'https://www.youtube.com/watch?v=D4qAQYLGZVM',
    featured: true,
    average_rating: 4.7,
    rating_count: 3300,
  },
  {
    title: 'Indian 2',
    description: 'Veerasekaran Senapathy returns from abroad to ignite a youth revolution against institutional corruption using social media exposés and varmam.',
    release_year: 2024,
    genre: 'Action',
    language: 'Tamil',
    duration: '3h 00m',
    director: 'S. Shankar',
    cast_members: 'Kamal Haasan, Siddharth, S. J. Suryah, Rakul Preet Singh, Priya Bhavani Shankar',
    poster_url: 'https://images.unsplash.com/photo-1518173946687-a4c8a383392e?q=80&w=800&auto=format&fit=crop',
    backdrop_url: backdropFallback,
    trailer_url: 'https://www.youtube.com/watch?v=EXeTwQWrcwY',
    featured: false,
    average_rating: 4.5,
    rating_count: 2800,
  },
  {
    title: 'Aayutha Ezhuthu',
    description: 'The lives of a fiery student leader, a ruthless henchman, and an affluent playboy intersect dramatically on the Napier Bridge in Chennai.',
    release_year: 2004,
    genre: 'Drama',
    language: 'Tamil',
    duration: '2h 40m',
    director: 'Mani Ratnam',
    cast_members: 'Suriya, Madhavan, Siddharth, Meera Jasmine, Trisha Krishnan, Esha Deol',
    poster_url: 'https://images.unsplash.com/photo-1493976040374-85c8e12f0c0e?q=80&w=800&auto=format&fit=crop',
    backdrop_url: backdropFallback,
    trailer_url: 'https://www.youtube.com/watch?v=sY1S34973zA',
    featured: false,
    average_rating: 4.8,
    rating_count: 2600,
  },
  {
    title: 'OK Kanmani (O Kadhal Kanmani)',
    description: 'Two ambitious modern youngsters in Mumbai opt for a live-in relationship without marital vows, guided by the enduring love of their elderly landlords.',
    release_year: 2015,
    genre: 'Romance',
    language: 'Tamil',
    duration: '2h 18m',
    director: 'Mani Ratnam',
    cast_members: 'Dulquer Salmaan, Nithya Menen, Prakash Raj, Leela Samson',
    poster_url: 'https://images.unsplash.com/photo-1539037116277-4db20889f2d4?q=80&w=800&auto=format&fit=crop',
    backdrop_url: backdropFallback,
    trailer_url: 'https://www.youtube.com/watch?v=r0f_k_sP9Zk',
    featured: false,
    average_rating: 4.8,
    rating_count: 2700,
  },
  {
    title: 'Madhumati',
    description: 'An ethereal romantic musical drama steeped in folklore, rebirth, and eternal love amidst the mist-covered hills of the Nilgiris.',
    release_year: 1989,
    genre: 'Romance',
    language: 'Tamil',
    duration: '2h 20m',
    director: 'Balu Mahendra',
    cast_members: 'Prabhu, Revathi, Shobana, Janagaraj',
    poster_url: 'https://images.unsplash.com/photo-1539037116277-4db20889f2d4?q=80&w=800&auto=format&fit=crop',
    backdrop_url: backdropFallback,
    trailer_url: 'https://www.youtube.com/watch?v=r0f_k_sP9Zk',
    featured: false,
    average_rating: 4.7,
    rating_count: 1800,
  },
  {
    title: 'Kushi',
    description: 'Two stubborn college sweethearts who are secretly in love allow petty ego clashes to delay their confession until mutual friends intervene.',
    release_year: 2000,
    genre: 'Romance',
    language: 'Tamil',
    duration: '2h 45m',
    director: 'S. J. Suryah',
    cast_members: 'Thalapathy Vijay, Jyothika, Vivek, Mumtaj, Vijayakumar',
    poster_url: 'https://images.unsplash.com/photo-1539037116277-4db20889f2d4?q=80&w=800&auto=format&fit=crop',
    backdrop_url: backdropFallback,
    trailer_url: 'https://www.youtube.com/watch?v=r0f_k_sP9Zk',
    featured: false,
    average_rating: 4.8,
    rating_count: 3100,
  },
  {
    title: 'Sachein',
    description: 'A cheerful, carefree college student in Ooty pursues an independent classmate who insists on true love without superficial romance.',
    release_year: 2005,
    genre: 'Romance',
    language: 'Tamil',
    duration: '2h 30m',
    director: 'John Mahendran',
    cast_members: 'Thalapathy Vijay, Genelia D Souza, Bipasha Basu, Vadivelu, Santhanam',
    poster_url: 'https://images.unsplash.com/photo-1539037116277-4db20889f2d4?q=80&w=800&auto=format&fit=crop',
    backdrop_url: backdropFallback,
    trailer_url: 'https://www.youtube.com/watch?v=r0f_k_sP9Zk',
    featured: false,
    average_rating: 4.7,
    rating_count: 2700,
  },
  {
    title: 'Pokkiri',
    description: 'A fearless underworld hitman working for rival gangs in Chennai is secretly revealed to be a dedicated undercover police IPS officer.',
    release_year: 2007,
    genre: 'Action',
    language: 'Tamil',
    duration: '2h 43m',
    director: 'Prabhu Deva',
    cast_members: 'Thalapathy Vijay, Asin, Prakash Raj, Vadivelu, Nassar',
    poster_url: 'https://images.unsplash.com/photo-1517604931442-7e0c8ed2963c?q=80&w=800&auto=format&fit=crop',
    backdrop_url: backdropFallback,
    trailer_url: 'https://www.youtube.com/watch?v=EXeTwQWrcwY',
    featured: false,
    average_rating: 4.8,
    rating_count: 3400,
  },
  {
    title: 'Vettaiyaadu Vilaiyaadu',
    description: 'A sophisticated Chennai DCP travels to New York City to track down a pair of psychopathic medical students executing gruesome murders.',
    release_year: 2006,
    genre: 'Thriller',
    language: 'Tamil',
    duration: '2h 58m',
    director: 'Gautham Vasudev Menon',
    cast_members: 'Kamal Haasan, Jyothika, Kamalinee Mukherjee, Daniel Balaji, Prakash Raj',
    poster_url: 'https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?q=80&w=800&auto=format&fit=crop',
    backdrop_url: backdropFallback,
    trailer_url: 'https://www.youtube.com/watch?v=znmZoVkCjpI',
    featured: true,
    average_rating: 4.9,
    rating_count: 3300,
  },
  {
    title: 'Panchatanthiram',
    description: 'A pilot and four of his best friends get entangled in an escalating comedic spiral involving diamond smuggling, misunderstandings, and an alleged dead body.',
    release_year: 2002,
    genre: 'Comedy',
    language: 'Tamil',
    duration: '2h 32m',
    director: 'K. S. Ravikumar',
    cast_members: 'Kamal Haasan, Simran, Ramya Krishnan, Jayaram, Ramesh Aravind',
    poster_url: 'https://images.unsplash.com/photo-1536440136628-849c177e76a1?q=80&w=800&auto=format&fit=crop',
    backdrop_url: backdropFallback,
    trailer_url: 'https://www.youtube.com/watch?v=sY1S34973zA',
    featured: false,
    average_rating: 4.9,
    rating_count: 3100,
  },
  {
    title: 'Michael Madana Kama Rajan',
    description: 'Quadruplet brothers separated at birth—a wealthy heir, a blind singer, a clumsy chef, and a petty rogue—trigger chaos when their paths collide.',
    release_year: 1990,
    genre: 'Comedy',
    language: 'Tamil',
    duration: '2h 45m',
    director: 'Singeetam Srinivasa Rao',
    cast_members: 'Kamal Haasan, Urvashi, Rupini, Kushboo, Nagesh, Delhi Ganesh',
    poster_url: 'https://images.unsplash.com/photo-1536440136628-849c177e76a1?q=80&w=800&auto=format&fit=crop',
    backdrop_url: backdropFallback,
    trailer_url: 'https://www.youtube.com/watch?v=sY1S34973zA',
    featured: false,
    average_rating: 4.9,
    rating_count: 2900,
  },
  {
    title: 'Avvai Shanmugi',
    description: 'An estranged father disguises himself as an elderly Brahmin nanny to stay close to his beloved daughter in his ex-wife mansion.',
    release_year: 1996,
    genre: 'Comedy',
    language: 'Tamil',
    duration: '2h 40m',
    director: 'K. S. Ravikumar',
    cast_members: 'Kamal Haasan, Meena, Gemini Ganesan, Nagesh, Heera Rajgopal',
    poster_url: 'https://images.unsplash.com/photo-1536440136628-849c177e76a1?q=80&w=800&auto=format&fit=crop',
    backdrop_url: backdropFallback,
    trailer_url: 'https://www.youtube.com/watch?v=sY1S34973zA',
    featured: false,
    average_rating: 4.9,
    rating_count: 3000,
  },
  {
    title: 'Vasool Raja MBBS',
    description: 'A lovable underworld debt collector pretends to be a medical student to please his parents, revolutionizing a hospital with empathy.',
    release_year: 2004,
    genre: 'Comedy',
    language: 'Tamil',
    duration: '2h 40m',
    director: 'Saran',
    cast_members: 'Kamal Haasan, Sneha, Prabhu, Prakash Raj, Nagesh, Crazy Mohan',
    poster_url: 'https://images.unsplash.com/photo-1536440136628-849c177e76a1?q=80&w=800&auto=format&fit=crop',
    backdrop_url: backdropFallback,
    trailer_url: 'https://www.youtube.com/watch?v=sY1S34973zA',
    featured: false,
    average_rating: 4.8,
    rating_count: 2800,
  },
  {
    title: 'Kalloori',
    description: 'Set in a rural government arts college, a tight-knit circle of friends welcomes an affluent city girl, ending with an unexpected real-life tragedy.',
    release_year: 2007,
    genre: 'Drama',
    language: 'Tamil',
    duration: '2h 15m',
    director: 'Balaji Sakthivel',
    cast_members: 'Akhil, Tamannaah Bhatia, Bharani, Hemalatha',
    poster_url: 'https://images.unsplash.com/photo-1493976040374-85c8e12f0c0e?q=80&w=800&auto=format&fit=crop',
    backdrop_url: backdropFallback,
    trailer_url: 'https://www.youtube.com/watch?v=bLvqoHBptjg',
    featured: false,
    average_rating: 4.7,
    rating_count: 2100,
  },
  {
    title: 'Kadhal',
    description: 'A young mechanic in Madurai falls in love with a high school girl from an influential caste, eloping to Chennai with devastating societal fallout.',
    release_year: 2004,
    genre: 'Drama',
    language: 'Tamil',
    duration: '2h 20m',
    director: 'Balaji Sakthivel',
    cast_members: 'Bharath, Sandhya, Sukumar, Dhandapani',
    poster_url: 'https://images.unsplash.com/photo-1507842229452-976932454b8d?q=80&w=800&auto=format&fit=crop',
    backdrop_url: backdropFallback,
    trailer_url: 'https://www.youtube.com/watch?v=bLvqoHBptjg',
    featured: false,
    average_rating: 4.8,
    rating_count: 2400,
  },
  {
    title: 'Vazhakku Enn 18/9',
    description: 'A hard-working roadside cook boy is falsely framed in an acid attack case committed by an arrogant wealthy neighbor boy.',
    release_year: 2012,
    genre: 'Crime',
    language: 'Tamil',
    duration: '1h 56m',
    director: 'Balaji Sakthivel',
    cast_members: 'Sri, Urmila Mahanta, Mithun Murali, Manisha Yadav',
    poster_url: 'https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?q=80&w=800&auto=format&fit=crop',
    backdrop_url: backdropFallback,
    trailer_url: 'https://www.youtube.com/watch?v=znmZoVkCjpI',
    featured: false,
    average_rating: 4.9,
    rating_count: 2500,
  },
];
